name: superlistas
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.1+4

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  path: ^1.9.1
  bcrypt: ^1.1.3
  auto_size_text: ^3.0.0
  share_plus: ^9.0.0
  file_selector: ^1.0.3

  # <<< MUDANÇA PRINCIPAL AQUI: Pacotes Firebase atualizados para compatibilidade >>>
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  firebase_remote_config: ^5.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/launcher_icon/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"
  min_sdk_android: 21