name: superlistas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  path: ^1.9.1
  bcrypt: ^1.1.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  auto_size_text: ^3.0.0
  share_plus: ^9.0.0
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # <<< CORREÇÃO: Pacote movido para dev_dependencies >>>
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    # <<< ADICIONADO: Garantir que a pasta do ícone seja incluída >>>
    - assets/launcher_icon/
    - assets/images/

# <<< ADICIONADO: Configuração para o gerador de ícones >>>
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"
  min_sdk_android: 21