import 'package:flutter/material.dart';

class CategoryIcons {
  static const Map<String, List<IconData>> iconGroups = {
    'Alimentos': [
      Icons.restaurant_menu,
      Icons.local_grocery_store,
      Icons.shopping_basket,
      Icons.kitchen,
      Icons.lunch_dining,
      Icons.egg,
      Icons.bakery_dining,
      Icons.ramen_dining,
      Icons.icecream,
      Icons.local_pizza,
      Icons.fastfood,
      Icons.coffee,
      Icons.local_bar,
      Icons.liquor,
      Icons.wine_bar,
      Icons.cake,
      Icons.breakfast_dining,
      Icons.dinner_dining,
      Icons.set_meal,
      Icons.tapas,
    ],
    'Casa e Limpeza': [
      Icons.home,
      Icons.cleaning_services,
      Icons.wash,
      Icons.dry_cleaning,
      Icons.iron,
      Icons.bathroom,
      Icons.bed,
      Icons.chair,
      Icons.weekend,
      Icons.countertops,
      Icons.blender,
      Icons.microwave,
      Icons.coffee_maker,
      Icons.kitchen,
      Icons.dining,
    ],
    'Saúde e Beleza': [
      Icons.health_and_safety,
      Icons.medical_services,
      Icons.medication,
      Icons.vaccines,
      Icons.face,
      Icons.spa,
      Icons.self_improvement,
      Icons.brush,
      Icons.soap,
      Icons.sanitizer,
      Icons.masks,
      Icons.healing,
      Icons.monitor_heart,
      Icons.psychology,
      Icons.shower,
    ],
    'Transporte': [
      Icons.directions_car,
      Icons.directions_bike,
      Icons.directions_bus,
      Icons.directions_subway,
      Icons.local_taxi,
      Icons.airport_shuttle,
      Icons.train,
      Icons.flight,
      Icons.electric_scooter,
      Icons.two_wheeler,
      Icons.local_shipping,
      Icons.local_gas_station,
      Icons.ev_station,
      Icons.car_repair,
      Icons.car_rental,
    ],
    'Tecnologia': [
      Icons.devices,
      Icons.computer,
      Icons.smartphone,
      Icons.tablet,
      Icons.headphones,
      Icons.keyboard,
      Icons.mouse,
      Icons.memory,
      Icons.cable,
      Icons.battery_charging_full,
      Icons.wifi,
      Icons.bluetooth,
      Icons.usb,
      Icons.sim_card,
      Icons.gamepad,
    ],
    'Educação e Trabalho': [
      Icons.school,
      Icons.work,
      Icons.business_center,
      Icons.book,
      Icons.menu_book,
      Icons.library_books,
      Icons.edit,
      Icons.create,
      Icons.brush_outlined,
      Icons.architecture,
      Icons.engineering,
      Icons.science,
      Icons.calculate,
      Icons.analytics,
      Icons.assignment,
    ],
    'Lazer e Entretenimento': [
      Icons.sports_soccer,
      Icons.sports_basketball,
      Icons.sports_tennis,
      Icons.fitness_center,
      Icons.pool,
      Icons.beach_access,
      Icons.music_note,
      Icons.movie,
      Icons.theater_comedy,
      Icons.museum,
      Icons.palette,
      Icons.photo_camera,
      Icons.videogame_asset,
      Icons.toys,
      Icons.celebration,
    ],
    'Finanças': [
      Icons.attach_money,
      Icons.payments,
      Icons.credit_card,
      Icons.account_balance,
      Icons.account_balance_wallet,
      Icons.savings,
      Icons.trending_up,
      Icons.trending_down,
      Icons.currency_exchange,
      Icons.receipt,
      Icons.receipt_long,
      Icons.point_of_sale,
      Icons.price_check,
      Icons.sell,
      Icons.shopping_cart,
    ],
    'Animais': [
      Icons.pets,
      Icons.cruelty_free,
      Icons.pest_control_rodent,
      Icons.catching_pokemon,
      Icons.emoji_nature,
      Icons.park,
      Icons.grass,
      Icons.eco,
      Icons.yard,
      Icons.forest,
    ],
    'Outros': [
      Icons.category,
      Icons.label_outline,
      Icons.bookmark_outline,
      Icons.star_outline,
      Icons.favorite_outline,
      Icons.flag,
      Icons.push_pin,
      Icons.location_on,
      Icons.access_time,
      Icons.schedule,
      Icons.today,
      Icons.event,
      Icons.alarm,
      Icons.notifications,
      Icons.help_outline,
    ],
  };

  static List<IconData> get allIcons {
    return iconGroups.values.expand((icons) => icons).toSet().toList();
  }

  static IconData getDefaultIcon() {
    return Icons.category;
  }
}